# Generated by Django 4.0.6 on 2022-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteudo da publicação')),
                ('publication_date', models.DateTimeField(verbose_name='Data de publicacao')),
                ('edition_date', models.DateTimeField(verbose_name='Data de edicao')),
                ('tags', models.ManyToManyField(to='news.tag')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['publication_date'],
            },
        ),
    ]
